services:
  - type: web
    name: cnu-cat-realtime
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: python server/app.py
